In [1]:

# MedPrice AI
# Prescription Price Comparison Assistant
# ITAI 2377 Project

import pandas as pd
import numpy as np
from IPython.display import display

print("Welcome to MedPrice AI!")
print("Project: Prescription Price Comparison Assistant")
print("Status: Initializing project environment...")

print("\nLibraries loaded successfully.")
print("Ready to build the medication price dataset.")

Welcome to MedPrice AI!
Project: Prescription Price Comparison Assistant
Status: Initializing project environment...

Libraries loaded successfully.
Ready to build the medication price dataset.

In [2]:

# STEP 2: Build the MedPrice AI Dataset

import pandas as pd

# Sample medication price data
# IMPORTANT: All prices below are fictional demo prices.

data = {
    "medication": [
        "Metformin",
        "Metformin",
        "Metformin",
        "Amoxicillin",
        "Amoxicillin",
        "Amoxicillin",
        "Atorvastatin",
        "Atorvastatin",
        "Atorvastatin",
        "Lisinopril",
        "Lisinopril",
        "Lisinopril",
        "Sertraline",
        "Sertraline",
        "Sertraline"
    ],
    "strength": [
        "500 mg", "500 mg", "500 mg",
        "500 mg", "500 mg", "500 mg",
        "20 mg", "20 mg", "20 mg",
        "10 mg", "10 mg", "10 mg",
        "50 mg", "50 mg", "50 mg"
    ],
    "quantity": [
        30, 30, 30, 21, 21, 21, 30, 30, 30,
        30, 30, 30, 30, 30, 30
    ],
    "pharmacy": [
        "Community Pharmacy",
        "City Pharmacy",
        "Neighborhood Drugs",
        "Community Pharmacy",
        "City Pharmacy",
        "Neighborhood Drugs",
        "Community Pharmacy",
        "City Pharmacy",
        "Neighborhood Drugs",
        "Community Pharmacy",
        "City Pharmacy",
        "Neighborhood Drugs",
        "Community Pharmacy",
        "City Pharmacy",
        "Neighborhood Drugs"
    ],
    "zip_code": [
        "77002", "77002", "77002",
        "77002", "77002", "77002",
        "77002", "77002", "77002",
        "77002", "77002", "77002",
        "77002", "77002", "77002"
    ],
    "price": [
        8.50, 6.25, 7.10,
        12.00, 9.50, 10.25,
        11.75, 8.00, 9.25,
        7.50, 5.99, 6.75,
        13.50, 10.00, 11.25
    ]
}

medication_df = pd.DataFrame(data)

# Display the dataset
print("MedPrice AI: Medication Price Dataset")
print("These are fictional demo prices, not current pharmacy quotes.")
print(f"\nNumber of records: {len(medication_df)}")

display(medication_df)

MedPrice AI: Medication Price Dataset
These are fictional demo prices, not current pharmacy quotes.

Number of records: 15

      medication strength  quantity            pharmacy zip_code  price
0      Metformin   500 mg        30  Community Pharmacy    77002   8.50
1      Metformin   500 mg        30       City Pharmacy    77002   6.25
2      Metformin   500 mg        30  Neighborhood Drugs    77002   7.10
3    Amoxicillin   500 mg        21  Community Pharmacy    77002  12.00
4    Amoxicillin   500 mg        21       City Pharmacy    77002   9.50
5    Amoxicillin   500 mg        21  Neighborhood Drugs    77002  10.25
6   Atorvastatin    20 mg        30  Community Pharmacy    77002  11.75
7   Atorvastatin    20 mg        30       City Pharmacy    77002   8.00
8   Atorvastatin    20 mg        30  Neighborhood Drugs    77002   9.25
9     Lisinopril    10 mg        30  Community Pharmacy    77002   7.50
10    Lisinopril    10 mg        30       City Pharmacy    77002   5.99
11    Lisinopril    10 mg        30  Neighborhood Drugs    77002   6.75
12    Sertraline    50 mg        30  Community Pharmacy    77002  13.50
13    Sertraline    50 mg        30       City Pharmacy    77002  10.00
14    Sertraline    50 mg        30  Neighborhood Drugs    77002  11.25

In [3]:

# Check the dataset structure

print("Dataset information:")
medication_df.info()

print("\nAvailable medications:")
print(medication_df["medication"].unique())

print("\nAvailable pharmacies:")
print(medication_df["pharmacy"].unique())

print("\nPrice summary:")
print(medication_df["price"].describe())

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   medication  15 non-null     object
 1   strength    15 non-null     object
 2   quantity    15 non-null     int64
 3   pharmacy    15 non-null     object
 4   zip_code    15 non-null     object
 5   price       15 non-null     float64
dtypes: float64(1), int64(1), object(4)
memory usage: 852.0+ bytes

Available medications:
['Metformin' 'Amoxicillin' 'Atorvastatin' 'Lisinopril' 'Sertraline']

Available pharmacies:
['Community Pharmacy' 'City Pharmacy' 'Neighborhood Drugs']

Price summary:
count    15.000000
mean      9.172667
std       2.285012
min       5.990000
25%       7.300000
50%       9.250000
75%      10.750000
max      13.500000
Name: price, dtype: float64

In [4]:

# STEP 3: Clean and Preprocess the Dataset

# Create a copy so the original dataset stays unchanged
cleaned_df = medication_df.copy()

# 1. Standardize medication names and text fields
cleaned_df["medication"] = (
    cleaned_df["medication"].str.strip().str.title()
)

cleaned_df["strength"] = cleaned_df["strength"].str.strip()
cleaned_df["pharmacy"] = cleaned_df["pharmacy"].str.strip()
cleaned_df["zip_code"] = cleaned_df["zip_code"].astype(str).str.strip()

# 2. Make sure prices are numeric
cleaned_df["price"] = pd.to_numeric(
    cleaned_df["price"], errors="coerce"
)

# 3. Remove records missing important information
required_columns = [
    "medication",
    "strength",
    "quantity",
    "pharmacy",
    "zip_code",
    "price"
]

cleaned_df = cleaned_df.dropna(subset=required_columns)

# 4. Remove invalid prices and quantities
cleaned_df = cleaned_df[
    (cleaned_df["price"] > 0) &
    (cleaned_df["quantity"] > 0)
].copy()

# 5. Remove duplicate records
cleaned_df = cleaned_df.drop_duplicates()

# 6. Reset row numbering
cleaned_df = cleaned_df.reset_index(drop=True)

print("Dataset cleaning completed!")
print(f"Original records: {len(medication_df)}")
print(f"Clean records: {len(cleaned_df)}")
print(f"Records removed: {len(medication_df) - len(cleaned_df)}")

display(cleaned_df)

Dataset cleaning completed!
Original records: 15
Clean records: 15
Records removed: 0

      medication strength  quantity            pharmacy zip_code  price
0      Metformin   500 mg        30  Community Pharmacy    77002   8.50
1      Metformin   500 mg        30       City Pharmacy    77002   6.25
2      Metformin   500 mg        30  Neighborhood Drugs    77002   7.10
3    Amoxicillin   500 mg        21  Community Pharmacy    77002  12.00
4    Amoxicillin   500 mg        21       City Pharmacy    77002   9.50
5    Amoxicillin   500 mg        21  Neighborhood Drugs    77002  10.25
6   Atorvastatin    20 mg        30  Community Pharmacy    77002  11.75
7   Atorvastatin    20 mg        30       City Pharmacy    77002   8.00
8   Atorvastatin    20 mg        30  Neighborhood Drugs    77002   9.25
9     Lisinopril    10 mg        30  Community Pharmacy    77002   7.50
10    Lisinopril    10 mg        30       City Pharmacy    77002   5.99
11    Lisinopril    10 mg        30  Neighborhood Drugs    77002   6.75
12    Sertraline    50 mg        30  Community Pharmacy    77002  13.50
13    Sertraline    50 mg        30       City Pharmacy    77002  10.00
14    Sertraline    50 mg        30  Neighborhood Drugs    77002  11.25

In [5]:

# Check the quality of the cleaned dataset

print("Missing values in each column:")
print(cleaned_df.isnull().sum())

print("\nDuplicate records remaining:")
print(cleaned_df.duplicated().sum())

print("\nInvalid prices remaining:")
print((cleaned_df["price"] <= 0).sum())

print("\nCleaned dataset summary:")
cleaned_df.info()

Missing values in each column:
medication    0
strength      0
quantity      0
pharmacy      0
zip_code      0
price         0
dtype: int64

Duplicate records remaining:
0

Invalid prices remaining:
0

Cleaned dataset summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   medication  15 non-null     object
 1   strength    15 non-null     object
 2   quantity    15 non-null     int64
 3   pharmacy    15 non-null     object
 4   zip_code    15 non-null     object
 5   price       15 non-null     float64
dtypes: float64(1), int64(1), object(4)
memory usage: 852.0+ bytes

In [6]:

# STEP 4: Build the MedPrice AI Comparison Engine

def compare_prices(medication, zip_code="77002", quantity=None):
    """
    Find and compare demo prices for a medication.
    Prices in this prototype are fictional.
    """

    # Clean the user's search input
    medication = medication.strip().title()
    zip_code = str(zip_code).strip()

    # Start with the cleaned dataset
    results = cleaned_df[
        (cleaned_df["medication"] == medication) &
        (cleaned_df["zip_code"] == zip_code)
    ].copy()

    # Filter by quantity if the user provides one
    if quantity is not None:
        results = results[
            results["quantity"] == int(quantity)
        ]

    # Handle medications that aren't found
    if results.empty:
        print("No matching medication records found.")
        print("Try another medication or ZIP code.")
        return None

    # Sort pharmacies from cheapest to most expensive
    results = results.sort_values("price").reset_index(drop=True)

    # Calculate the price difference
    lowest_price = results["price"].min()
    highest_price = results["price"].max()
    potential_difference = highest_price - lowest_price

    print(f"Medication: {medication}")
    print(f"ZIP code: {zip_code}")
    print("\nFictional demo prices — not live pharmacy quotes.\n")

    display(
        results[["medication", "strength", "quantity",
                 "pharmacy", "zip_code", "price"]]
    )

    print(f"\nLowest listed demo price: ${lowest_price:.2f}")
    print(f"Highest listed demo price: ${highest_price:.2f}")
    print(f"Difference between prices: ${potential_difference:.2f}")

    return results

In [7]:

# Test 1: Compare prices for Metformin
metformin_results = compare_prices(
    medication="Metformin",
    zip_code="77002",
    quantity=30
)

Medication: Metformin
ZIP code: 77002

Fictional demo prices — not live pharmacy quotes.

  medication strength  quantity            pharmacy zip_code  price
0  Metformin   500 mg        30       City Pharmacy    77002   6.25
1  Metformin   500 mg        30  Neighborhood Drugs    77002   7.10
2  Metformin   500 mg        30  Community Pharmacy    77002   8.50

Lowest listed demo price: $6.25
Highest listed demo price: $8.50
Difference between prices: $2.25

In [8]:

# Test 2: Compare prices for Atorvastatin
atorvastatin_results = compare_prices(
    medication="Atorvastatin",
    zip_code="77002",
    quantity=30
)

Medication: Atorvastatin
ZIP code: 77002

Fictional demo prices — not live pharmacy quotes.

     medication strength  quantity            pharmacy zip_code  price
0  Atorvastatin    20 mg        30       City Pharmacy    77002   8.00
1  Atorvastatin    20 mg        30  Neighborhood Drugs    77002   9.25
2  Atorvastatin    20 mg        30  Community Pharmacy    77002  11.75

Lowest listed demo price: $8.00
Highest listed demo price: $11.75
Difference between prices: $3.75

In [10]:

# Test 3: Test an unavailable medication
test_results = compare_prices(
    medication="UnknownMedicine",
    zip_code="77407"
)

No matching medication records found.
Try another medication or ZIP code.